<div class="entry-edit">
	<div class="entry-edit-head">
		<h3 class="icon-head head-edit-form fieldset-legend"><?php echo 'Template Tag'; ?></h3>
	</div>
		
			
		
<textarea id="flexslider-template-tag" rows="3" cols="80" onclick="this.focus();this.select()" readonly="readonly">{{block class="Magebees\Finder\Block\Finder" template="finder.phtml" finder_id="<?php echo $block->getFinderData(); ?>"}}</textarea>

</div>
<br><br>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h3 class="icon-head head-edit-form fieldset-legend"><?php echo 'XML Code'; ?></h3>
	</div>
		
		
		
<textarea id="flexslider-code" rows="7" cols="80" onclick="this.focus();this.select()" readonly="readonly"><referenceContainer name="content">
	<block class="Magebees\Finder\Block\Finder" name="finder<?php echo $block->getFinderData(); ?>" template="template.phtml">
		<action method="setCode"><code><?php echo $block->getFinderData(); ?></code></action>
	</block>
</referenceContainer></textarea>
</div>

<br><br>
<div class="entry-edit">
	<div class="entry-edit-head">
		<h3 class="icon-head head-edit-form fieldset-legend"><?php echo 'Call Via Frontend Template File'; ?></h3>
	</div>
	
		
		
<textarea id="flexslider-template-tag" rows="3" cols="80" onclick="this.focus();this.select()" readonly="readonly"><?php echo '<?php echo  $this->getLayout()->createBlock("Magebees\Finder\Block\Finder")->setCode('. $block->getFinderData().')->setTemplate("template.phtml")->toHtml() ?>'; ?></textarea>
</div>

