<?php 
/* @var block \Magebees\Finder\Block\Finder */
if($block->getCategoryPageEnabled()):
	$finderId = "";
	$finderArr = array();
	$finderStr = null;
	$p = 0;
	$path = $this->getRequest()->getRequestString();
	$p = strpos($path, 'finder');
	if($p){
		$path = trim($path, '/');
		$path = strrchr($path,'finder');
		$finderparams = explode('/',$path);
		$finderStr =$finderparams[2];
		$finderArr = explode('-',$finderStr);
		$finder_param_id = $finderparams[1];
		
	}
	$finderIdsByCategoryArray = array();
	$category_skus = array();
	$finderIdsByCategoryArray = $block->getFinderIdsByCategoryId();
	$category_skus = $block->getProductsByCategoryId();
?>
<?php foreach($finderIdsByCategoryArray as $finderId): ?>
	<?php $dropdownCollection = $block->getDropdownsCollectionByFinderId($finderId); ?>
	<?php $finderCollection = $block->getFinderById($finderId); ?>
	<?php $searchurl = $this->getUrl('finder'.'/'.$finderId); ?>
	<?php $isDisplay = $block->displayFinder($finderId,$category_skus); ?>
	<?php if($finderCollection->getStatus() && $isDisplay): ?>
		<div class="finderProducts <?php echo $finderCollection->getDropdownStyle() ?>">
			<form action="<?php //echo $searchurl; ?>" id="finderform_<?php echo $finderId?>" name="finderform"  class="finderform" method="post">
				<h3 class="finder_header"><?php echo __($finderCollection->getTitle()); ?></h3>
				<div id="<?php echo "finderDropdowns_".$finderId ?>" class="finderDropdowns">
				<ul class="clearfix">
					<?php
					$i=1;
					$count = $dropdownCollection->count();	
					$selectedValues = "";
					$finderStr = "";
					foreach($dropdownCollection as $dropdown):
						$productarray = array();
						$field= "field".$i;
					?>
						<li id="drop_<?php echo $finderId ?>_<?php echo $i?>" class="drop_<?php echo $i; ?> column<?php echo $finderCollection->getNoOfColumns() ?>">
							<label><?php echo __($dropdown->getName().": "); ?></label>
							<select name="finder_<?php echo $i ?>" field-id="<?php echo $i ?>" drop-down-counts="<?php echo $count ?>" drop-down-id="<?php echo $dropdown->getId() ?>" id="finder_<?php echo $finderId ?>_<?php echo $i?>" >
								<option value=""><?php echo __("Please Select"); ?></option>
								<?php if($i==1 || !empty($finderArr))
								{
									$productCollection = $block->getProductsByFinderIdForCategory($finderId,$dropdown->getSort(),$i,$category_skus,$finderStr);
									foreach($productCollection as $product)	{
										$key= $product->getData($field);
										if(!array_key_exists($key,$productarray)){
											?>
												<option value="<?php echo $product->getData($field);?>" <?php if(!empty($finderArr)){ 
																				if(array_key_exists($i-1,$finderArr) && $finderArr[$i-1] == $key && $finder_param_id==$finderId){ 
																					?> selected="selected" <?php 
																					}
																				}?> >
													<?php echo $product->getData($field); ?>
												</option>
											<?php
											$productarray[$key]=$key;
										}
									}
								}
								?>
							</select>
						</li>
						<?php $i++; ?>
					<?php endforeach; ?>
				</ul>
				</div>
				
				<button id="find_<?php echo $finderId?>" type="submit" title="Find" value="1" name="find" class="action subscribe primary" disabled="" ><span><?php echo $block->getFindBtnText() ?></span></button>
				<button id="reset_<?php echo $finderId ?>" drop-down-counts="<?php echo $count ?>" name="reset" value="1" title="Reset" class="button" <?php if($p): ?> type="submit" <?php else: ?> type="button" <?php endif; ?> ><span><span><?php echo __($block->getResetBtnText()) ?></span></span></button>
			</form>
		</div>
		<?php $url = $this->getUrl('finder/index/finder'); ?>
		<script type="text/javascript">
			requirejs(['jquery','cwsfinder'], function(jQuery){
				var finderMage = {'finderId':'<?php echo $finderId ?>','url':'<?php echo $url ?>','searchurl':'<?php echo $searchurl ?>','autosearch':<?php echo $block->getAutosearch() ?>,'category_id':'<?php echo $block->getCurrentCategory()->getId() ?>'};
				var dropdown_div_id = '<?php echo "#finderDropdowns_".$finderId ?>';
				jQuery(dropdown_div_id).cwsfinder(finderMage);
			});	
		</script>
	<?php endif; ?>
<?php endforeach; ?>

<?php endif; ?>

