<?php 
/* @var block \Magebees\Finder\Block\Finder */
if($block->getEnabled()): 
$finderId = 1; ?>
<?php
	$finderArr = array();
	$finderStr = null;
	$search = 0;
	if($finderId==""){
		$path = $this->getRequest()->getRequestString();
		$search = strpos($path, 'finder');
		if($search){
			$finderparams = array();
			$path = trim($path, '/');
			$finderparams = explode('/',$path);
			if(isset($finderparams[2])){
				$finderStr = $finderparams[2];
				$finderStrArr=explode('?',$finderStr);
				$finderStr=current($finderStrArr);
				$finderStr = urldecode($finderStr);
				$finderArr = explode('-',$finderStr);
			}
			$finderId = $finderparams[1];
		}
	}
?>
<?php $dropdownCollection = $block->getDropdownsCollectionByFinderId($finderId); ?>
<?php $finderCollection = $block->getFinderById($finderId); ?>
<?php $searchurl = $this->getUrl('finder'.'/'.$finderId); ?>
<?php if($finderCollection->getStatus()): ?>
<div class="finderProducts <?php echo $finderCollection->getDropdownStyle() ?>">
	<form action="<?php echo $searchurl; ?>" id="finderform_<?php echo $finderId ?>" name="finderform"  class="finderform" method="post">
		<h3 class="finder_header"><?php echo __($finderCollection->getTitle()); ?></h3>
		<div id="<?php echo "finderDropdowns_".$finderId ?>" class="finderDropdowns">
		<ul class="clearfix">
			<?php
			$i=1;
			$count=$dropdownCollection->count();	
			foreach($dropdownCollection as $dropdown):
				$productarray=array();
				$field= "field".$i;
			?>
				<li id="drop_<?php echo $finderId ?>_<?php echo $i?>" class="drop_<?php echo $i; ?> column<?php echo $finderCollection->getNoOfColumns() ?>">
                                        <?php if($dropdown->getName()=="year") :?>
                                <label>year: </label>
                                <select name="finder_1" field-id="1" drop-down-counts="4" drop-down-id="1" id="finder_1_1">
                                    <option value="">Please Select</option>
				    <option value="2017">2017</option>
                                    <option value="2016">2016</option>
                                    <option value="2015">2015</option>
                                    <option value="2014">2014</option>
                                    <option value="2013">2013</option>
                                    <option value="2012">2012</option>
                                    <option value="2011">2011</option>
                                    <option value="2010">2010</option>
                                    <option value="2009">2009</option>
                                    <option value="2008">2008</option>
                                    <option value="2007">2007</option>
                                    <option value="2006">2006</option>
                                    <option value="2005">2005</option>
                                    <option value="2004">2004</option>
                                    <option value="2003">2003</option>
                                    <option value="2002">2002</option>
                                    <option value="2001">2001</option>
                                    <option value="2000">2000</option>
                                    <option value="1999">1999</option>
                                    <option value="1998">1998</option>
                                    <option value="1997">1997</option>
                                    <option value="1996">1996</option>
                                    <option value="1995">1995</option>
                                    <option value="1994">1994</option>
                                    <option value="1993">1993</option>
                                    <option value="1992">1992</option>
                                    <option value="1991">1991</option>                                    
                                    <option value="1989">1989</option>                                    
                                    <option value="1988">1988</option>
                                    <option value="1987">1987</option>
                                    <option value="1986">1986</option>
                                    <option value="1985">1985</option>
                                    <option value="1984">1984</option>
                                    <option value="1983">1983</option>
                                    <option value="1982">1982</option>
                                    <option value="1981">1981</option>
                                    <option value="1980">1980</option>
                                    <option value="1979">1979</option>
                                    <option value="1978">1978</option>
                                    <option value="1977">1977</option>
                                    <option value="1976">1976</option>
                                    <option value="1975">1975</option>
                                    <option value="1974">1974</option>
                                    <option value="1973">1973</option>
                                    <option value="1972">1972</option>
                                    <option value="1971">1971</option>
                                    <option value="1970">1970</option>
                                    <option value="1969">1969</option>
                                    <option value="1968">1968</option>
                                    <option value="1967">1967</option>
                                    <option value="1966">1966</option>
                                    <option value="1965">1965</option>
                                    <option value="1964">1964</option>
                                </select>
                            <?php else: ?>       

					<label><?php echo __($dropdown->getName().": "); ?></label>
					<select name="finder_<?php echo $i ?>" field-id="<?php echo $i ?>" drop-down-counts="<?php echo $count ?>" drop-down-id="<?php echo $dropdown->getId() ?>" id="finder_<?php echo $finderId ?>_<?php echo $i?>" >
						<option value=""><?php echo __("Please Select"); ?></option>
						<?php if($i==1 || !empty($finderArr))
						{
							$productCollection = $block->getProductsByFinderId($finderId,$dropdown->getSort(),$i,$finderStr);
							if($productCollection){
							foreach($productCollection as $product)	{
								$key= $product->getData($field);
								if(!array_key_exists($key,$productarray))
								{
									?>
										<option value="<?php echo $product->getData($field);?>" <?php if(count($finderArr)!=""){ 
																		if(array_key_exists($i-1,$finderArr) && $finderArr[$i-1] == $key){ 
																			?> selected="selected" <?php 
																			}
																		}?> >
											<?php echo $product->getData($field); ?>
										</option>
										
									<?php
									$productarray[$key]=$key;
								}
							}
							}
						}
						?>
					</select>
                                      <?php endif; ?>
				</li>
				<?php $i++; ?>
			<?php endforeach; ?>
		</ul>
		</div>
		<button id="find_<?php echo $finderId ?>" type="submit" title="Find" value="1" name="find" class="action subscribe primary" disabled="" ><span><?php echo __($block->getFindBtnText()) ?></span></button>
		<button id="reset_<?php echo $finderId ?>" drop-down-counts="<?php echo $count ?>" name="reset" value="1" title="Reset" class="button" <?php if($search): ?> type="submit" <?php else: ?> type="button" <?php endif; ?> ><span><span><?php echo __($block->getResetBtnText()) ?></span></span></button>
	</form>
</div>
<?php $url = $this->getUrl('finder/index/finder'); ?>
<script type="text/javascript">
	requirejs(['jquery','cwsfinder'], function(jQuery){
		var finderMage = {'finderId':'<?php echo $finderId ?>','url':'<?php echo $url ?>','searchurl':'<?php echo $searchurl ?>','autosearch':<?php echo $block->getAutosearch() ?>};
		var dropdown_div_id = '<?php echo "#finderDropdowns_".$finderId ?>';
		jQuery(dropdown_div_id).cwsfinder(finderMage);
                window.onload=function(){
            var url = document.location.toString();
                if(url.substring(29,35)=="finder"){
                           var url2 = (url.substring(38));
                                if(url2.indexOf("?") !== -1){
                                    var num  =  url2.indexOf("?");                                  
                                    var url2 = url2.substring(0,num);                                  
                                      }
                                    var str = url2.split("-");                                
                                    document.getElementById("finder_1_1").value=str[0];
                                    document.getElementById("finder_1_2").options.add(new Option(str[1], str[1]));
                                    document.getElementById("finder_1_2").value=str[1];
                                                 if(str[2]){
                                                     document.getElementById("finder_1_3").options.add(new Option(str[2], str[2]));
                                                     document.getElementById("finder_1_3").value=str[2];
                                                 }
                                                  if(str[3]){
                                                      document.getElementById("finder_1_4").options.add(new Option(str[3], str[3]));
                                                      document.getElementById("finder_1_4").value=str[3];
                                                  }

                                }

              }    
 });	
</script>
<?php endif; ?>
<?php endif; ?>
