<?php
?>
<div class="finderProducts"  style="border:solid 1px #bbb;background-color:#efefef;">
    <form action="<?php echo $block->get_url().'com/index/Getprod'; ?>" id="finderform_1" name="finderform" class="finderform" method="get">
    <div class="select-part">
        <div class="finder-part">Select Your Vehicle</div>
        <div id="finderDropdowns_1" class="finderDropdowns">
        <ul>
        <li class="select-year">
                <select name="year" field-id="1"  id="finder_1_1">
                    <option value="year" selected="selected" >Please Select Year</option>
                    <option value="2016">2016</option>
		    <option value="2015">2015</option>
		    <option value="2014">2014</option>
		    <option value="2013">2013</option>
		    <option value="2012">2012</option>
		    <option value="2011">2011</option>
		    <option value="2010">2010</option>
		    <option value="2009">2009</option>
		    <option value="2008">2008</option>
		    <option value="2007">2007</option>
		    <option value="2006">2006</option>
		    <option value="2005">2005</option>
		    <option value="2004">2004</option>
		    <option value="2003">2003</option>
		    <option value="2002">2002</option>
		    <option value="2001">2001</option>
		    <option value="2000">2000</option>
		    <option value="1999">1999</option>
		    <option value="1998">1998</option>
		    <option value="1997">1997</option>
		    <option value="1996">1996</option>
		    <option value="1995">1995</option>
		    <option value="1994">1994</option>
		    <option value="1993">1993</option>
		    <option value="1992">1992</option>
		    <option value="1991">1991</option>
		    <option value="1991">1991</option>
		    <option value="1989">1989</option>
		    <option value="1989">1989</option>
		    <option value="1988">1988</option>
		    <option value="1987">1987</option>
		    <option value="1986">1986</option>
		    <option value="1985">1985</option>
		    <option value="1984">1984</option>
		    <option value="1983">1983</option>
		    <option value="1982">1982</option>
		    <option value="1981">1981</option>
		    <option value="1980">1980</option>
		    <option value="1979">1979</option>
                    <option value="1978">1978</option>
                    <option value="1977">1977</option>
		    <option value="1976">1976</option>
		    <option value="1975">1975</option>
		    <option value="1974">1974</option>
		    <option value="1973">1973</option>
		    <option value="1972">1972</option>
		    <option value="1971">1971</option>
		    <option value="1970">1970</option>
		    <option value="1969">1969</option>
		    <option value="1968">1968</option>
		    <option value="1967">1967</option>
		    <option value="1966">1966</option>
		     </select>
                </li>
                <li class="select-make">
                <select name="make" field-id="2"  id="finder_1_2"  disabled="disabled">
                    <option value="make" selected="selected">Please Select Make</option>
                </select>
                </li>
                <li class="select-model">
                <select name="model" field-id="3"  id="finder_1_3" disabled="disabled">
                    <option  id="3" value="model" selected="selected">Please Select Model</option>
                </select>
                </li>
        </div>
        <div class="finder-button">
            <div  id="sub"  onclick="ff()" ><a href="javascript:document:finderform_1.submit();" id="find_1"  type="submit"  value="Search">Search</a></div>
            <div id="rreset"><a type="reset" alt="reset" value="Reset">Reset</a></div>
            <input type="hidden" name="p" value="1" />
            <input type="hidden" name="product_list_limit" value="30" />
        </div>
        </div>
    </form>
</div>

<script type="text/javascript">// <![CDATA[
    require([
        'jquery',
        'owl.carousel/owl.carousel.min'
    ], function ($) {
        $("#finder_1_1").css({"border":"2px", "color":"rgb(10, 10, 10)", "border-style":"solid"});
        $("#rreset").click(function(){
            $("#finder_1_1").css({"border":"2px", "color":"rgb(10, 10, 10)", "border-style":"solid"});
            $("#finder_1_2").attr("disabled",true);
            $("#finder_1_3").attr("disabled",true);
            $("#finder_1_2").empty();
            $("#finder_1_3").empty();
            $("#finder_1_1").append("<option value=year selected=selected >"+"Please Select Year"+"</option>");
            $("#finder_1_2").append("<option>"+"Please Select Make"+"</option>");
            $("#finder_1_3").append("<option>"+"Please Select Model"+"</option>");
            $("#finder_1_2").css({"border":"", "color":"", "border-style":""});
            $("#finder_1_3").css({"border":"", "color":"", "border-style":""});
        });

        $("#finder_1_1").change(function(){
            $("#finder_1_1 option[value='year']").remove();
            $("#finder_1_2").empty();
            $("#finder_1_2").append("<option  value=make >"+"Please Select Make"+"</option>");
            $("#finder_1_3").empty();
            $("#finder_1_3").append("<option  >"+"Please Select Model"+"</option>");
            $("#finder_1_1").css({"border":"", "color":"", "border-style":""});
            $("#finder_1_2").css({"border":"2px", "color":"rgb(10, 10, 10)", "border-style":"solid"});
            var year=$("#finder_1_1").val();
            $.post("<?php echo $block->get_url().'com/index/syear';?>", { "year": year },
                function(data){
                    for(var i=0,l=data.length;i<l;i++){
                        for(var key in data[i]){
                            $("#finder_1_2").append("<option value='" +data[i][key]+ "'>" +data[i][key] + "</option>");                                $("#finder_1_2").attr("disabled",false);
                        }
                    }
                });
        });
        $("#finder_1_2").change(function(){
            $("#finder_1_3").empty();
            $("#finder_1_2 option[value='make']").remove();
            $("#finder_1_3").append("<option>"+"Please Select Model"+"</option>");
            $("#finder_1_2").css({"border":"", "color":"", "border-style":""});
            $("#finder_1_3").css({"border":"2px", "color":"rgb(10, 10, 10)", "border-style":"solid"});
            var year =$("#finder_1_1").find("option:selected").text();
            var make=$("#finder_1_2").find("option:selected").text();
            $.post("<?php echo $block->get_url().'com/index/smodel'; ?>", {"year": year,"make": make},
                function(data){
                    for(var i=0,l=data.length;i<l;i++){
                        for(var key in data[i]){
                            $("#finder_1_3").append("<option value='" +data[i][key]+ "'>" +data[i][key] + "</option>");
                            $("#finder_1_3").attr("disabled",false);
                        }
                    }
                });
        });

        $("#finder_1_3").change(function(){
            $("#finder_1_3").css({"border":"", "color":"", "border-style":""});
        });


    });

    function  ff()
    {
        var obj = document.getElementById("finder_1_3");
        var index = obj.selectedIndex;
        var text = obj.options[index].text;
        if(document.getElementById("finder_1_2").disabled ==true)
        {
            document.getElementById("find_1").href="javascript:void(0);";
            alert("Please select a year");
        }
        else if(document.getElementById("finder_1_3").disabled ==true)
        {
            document.getElementById("find_1").href="javascript:void(0);";
            alert("Please select a make");
        }
        else if(text =="Please Select Model")
        {
            document.getElementById("find_1").href="javascript:void(0);";
            alert("Please select a model");
        }
        else
        {
            document.getElementById("find_1").href="javascript:document:finderform_1.submit();";
        }
    }
    // ]]></script>
